services:
  - type: web
    name: fcc-proxy
    runtime: python
    repo: https://github.com/raghavshahhh/proxy
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT --timeout-graceful-shutdown 5
    envVars:
      - key: NVIDIA_NIM_API_KEY
        sync: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: "8082"
      - key: PYTHON_VERSION
        value: "3.14.0"